#!/bin/bash

# site init
# GNU Affero General Public License v3.0

# texts elements
# html text
html_text="<!DOCTYPE html>
<html lang=\"en\">
  <head>
    <meta charset=\"UTF-8\"/>
    <meta name=\"viewport\" content=\"width=device-width initial-scale=1.0\"/>
    <meta name=\"apple-mobile-web-app-capable\" content=\"yes\"/>
    <meta name=\"apple-mobile-web-app-status-bar-style\" content=\"black-translucent\"/>
    <meta name=\"mobile-web-app-capable\" content=\"yes\"/>
    <link rel=\"stylesheet\" href=\"./../../css/pages.css\"/>
    <link rel=\"stylesheet\" href=\"./assets/css/index.css\"/>
    <title></title>
  </head>
  <body>
    <script src=\"./assets/js/script.js\"></script>
  </body>
</html>"

# css text
css_text="
:root {
  --bg: ;
  --fg: ;
  --acnt-a: ;
  --acnt-b: ;
  --acnt-c: ;
  --acnt-d: ;
  --clr: #00000000;
}

@font-face {
  src: url(./../fonts/);
  font-family: ;
}

* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
  text-decoration: unset;
  border: unset;
  outline: unset;
  scroll-behavior: smooth;
  -webkit-tap-highlight-color: rgba(0, 0, 0, 0);
  user-select: none;
}

body, html {
}
"

# js text
js_text="
"

main() {
  
  clear;
  echo -e "\n";

  # site name
  read -p "site name: " site_name;
  mkdir "$site_name";
  echo -e "\n";

  # build directory tree
  mkdir -p ./"$site_name"/assets/css/;
  mkdir -p ./"$site_name"/assets/js/;
  mkdir -p ./"$site_name"/assets/fonts/;
  mkdir -p ./"$site_name"/assets/images/icons/;
  mkdir -p ./"$site_name"/assets/images/photos/;

  # initialize html
  touch ./"$site_name"/index.html;
  echo "$html_text" > ./"$site_name"/index.html;

  # initialize css
  touch ./"$site_name"/assets/css/index.css;
  echo "$css_text" > ./"$site_name"/assets/css/index.css;
  
  # initialize js
  touch ./"$site_name"/assets/js/script.js;
  echo "$js_text" > ./"$site_name"/assets/js/script.js;

  echo -e "\n";
}

main
